#ifndef PSTADE_EGG_DETAIL_EGG_HPP
#define PSTADE_EGG_DETAIL_EGG_HPP


// PStade.Egg
//
// Copyright Shunsuke Sogame 2007-2008.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)


// This header is guaranteed to be a part of Egg in future version.
// This is placed in /detail/ so that you should shy away inclusion.


#include "../adapted_to_base.hpp"
#include "../after.hpp"
#include "../always.hpp"
#include "../ambi.hpp"
#include "../apply.hpp"
#include "../apply_decl.hpp"
#include "../arg.hpp"
#include "../auto_new.hpp"
#include "../auto_object.hpp"
#include "../automatic.hpp"
#include "../before.hpp"
#include "../bll.hpp"
#include "../bll_bindable.hpp"
#include "../bll_defer.hpp"
#include "../braced1_construct.hpp"
#include "../braced2_construct.hpp"
#include "../by_cref.hpp"
#include "../by_perfect.hpp"
#include "../by_ref.hpp"
#include "../by_value.hpp"
#include "../compose.hpp"
#include "../compose2.hpp"
#include "../config.hpp"
#include "../const.hpp"
#include "../construct.hpp"
#include "../constructor.hpp"
#include "../copy.hpp"
#include "../copy_assign.hpp"
#include "../curry.hpp"
#include "../deduced_form.hpp"
#include "../deferred.hpp"
#include "../delete.hpp"
#include "../delete_array.hpp"
#include "../do_swap.hpp"
#include "../fix.hpp"
#include "../flip.hpp"
#include "../forward.hpp"
#include "../from.hpp"
#include "../function.hpp"
#include "../function_extension.hpp"
#include "../function_facade.hpp"
#include "../function_fwd.hpp"
#include "../functional.hpp"
#include "../fuse.hpp"
#include "../generator.hpp"
#include "../identity.hpp"
#include "../iequal_to.hpp"
#include "../indirect.hpp"
#include "../infix.hpp"
#include "../integral.hpp"
#include "../is_same.hpp"
#include "../keyword.hpp"
#include "../lexical.hpp"
#include "../locale.hpp"
#include "../make_function.hpp"
#include "../memoize.hpp"
#include "../mono.hpp"
#include "../move_assign.hpp"
// #include "../named.hpp"
#include "../new.hpp"
#include "../new_array.hpp"
#include "../ptr_new.hpp"
#include "../shared_new.hpp"
#include "../shared_new_array.hpp"
#include "../not.hpp"
#include "../parallel.hpp"
#include "../perfect.hpp"
#include "../pipable.hpp"
#include "../register_nullary_result.hpp"
#include "../regular.hpp"
#include "../result_of_ref.hpp"
#include "../return.hpp"
#include "../shared_object.hpp"
#include "../specified.hpp"
#include "../static.hpp"
#include "../static_down.hpp"
#include "../static_downcast.hpp"
#include "../strong_assign.hpp"
#include "../tagged.hpp"
#include "../to_ref.hpp"
#include "../to_shared_ptr.hpp"
#include "../to_string.hpp"
#include "../to_value.hpp"
#include "../tuple.hpp"
#include "../uncurry.hpp"
#include "../unfuse.hpp"
#include "../unwrap_ref.hpp"
#include "../variadic.hpp"
#include "../variadic1_construct.hpp"


#endif
