#ifndef PSTADE_WINE_HPP
#define PSTADE_WINE_HPP


// PStade.Wine Utility Library
//
// Copyright Shunsuke Sogame 2005-2006.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)


#include "./adaptable.hpp"
#include "./adl_barrier.hpp"
#include "./affect.hpp"
#include "./any_movable.hpp"
#include "./arraya.hpp"
#include "./automatic.hpp"
#include "./auxiliary.hpp"
#include "./base_from.hpp"
#include "./callable.hpp"
#include "./callable_by_value.hpp"
#include "./check.hpp"
#include "./clone_ptr.hpp"
#include "./compose.hpp"
#include "./concept.hpp"
#include "./const_overloaded.hpp"
#include "./constant.hpp"
#include "./construct.hpp"
#include "./contract.hpp"
#include "./copy_assign.hpp"
#include "./copy_construct.hpp"
#include "./deduced_const.hpp"
#include "./deferred.hpp"
#include "./disable_if_copy.hpp"
#include "./do_swap.hpp"
#include "./dont_care.hpp"
#include "./enable_if.hpp"
#include "./for_debug.hpp"
#include "./function.hpp"
#include "./functional.hpp"
#include "./fuse.hpp"
#include "./has_xxx.hpp"
#include "./if_debug.hpp"
#include "./implicitly_defined.hpp"
#include "./in_unnamed.hpp"
#include "./indirect.hpp"
#include "./instance.hpp"
#include "./integral_cast.hpp"
// #include "./ios_init.hpp"
#include "./is_convertible.hpp"
#include "./is_ndebug.hpp"
#include "./is_returnable.hpp"
#include "./is_same.hpp"
#include "./lambda_bind.hpp"
#include "./lexical_cast.hpp"
#include "./locale.hpp"
#include "./locale_saver.hpp"
#include "./new_delete.hpp"
#include "./nonconstructible.hpp"
#include "./nullptr.hpp"
#include "./object_generator.hpp"
#include "./pass_by.hpp"
#include "./pause.hpp"
#include "./perfect.hpp"
#include "./pipable.hpp"
#include "./polymorphic.hpp"
#include "./preprocessor.hpp"
#include "./provide_result_of_sig.hpp"
#include "./provide_sig.hpp"
#include "./remove_cvr.hpp"
#include "./require.hpp"
// #include "./result_of_lambda.hpp"
#include "./singleton.hpp"
#include "./specified.hpp"
#include "./statement.hpp"
#include "./static_c.hpp"
#include "./static_downcast.hpp"
#include "./template_arguments.hpp"
#include "./to_ref.hpp"
#include "./to_shared_ptr.hpp"
#include "./to_value.hpp"
#include "./tuple.hpp"
#include "./unevaluated.hpp"
#include "./unfuse.hpp"
// #include "./unit_test.hpp"
#include "./unparenthesize.hpp"
#include "./unused.hpp"
#include "./use_default.hpp"
#include "./used.hpp"
#include "./ustring.hpp"
#include "./verify.hpp"
#include "./what.hpp"
#include "./yes_no.hpp"


#endif
