#ifndef PSTADE_LIBS_OVEN_TEST_DETAIL_CONFIG_HPP
#define PSTADE_LIBS_OVEN_TEST_DETAIL_CONFIG_HPP

#include <boost/mpl/aux_/config/gcc.hpp>

#if (BOOST_WORKAROUND(BOOST_MPL_CFG_GCC, >= 0x0405) && defined(__GXX_EXPERIMENTAL_CXX0X__)) || \
	BOOST_WORKAROUND(BOOST_MSVC, >= 1600)
	#define PSTADE_OVEN_TEST_HAS_0X_LAMBDA_EXPRESSION
#endif

#endif
