#pragma once

#include <boost/config.hpp>


#if (_ATL_VER >= 0x0700)
	#define PSTADE_TOMATO_WORKAROUND_ATL_CSIMPLEARRAY_TEMPLATE_PARAMS class KeyT, class EqualT
	#define PSTADE_TOMATO_WORKAROUND_ATL_CSIMPLEARRAY_TEMPLATE_ARGS KeyT, EqualT
#else
	#define PSTADE_TOMATO_WORKAROUND_ATL_CSIMPLEARRAY_TEMPLATE_PARAMS class KeyT
	#define PSTADE_TOMATO_WORKAROUND_ATL_CSIMPLEARRAY_TEMPLATE_ARGS KeyT
#endif


#if (_MSC_VER >= 1310)
	#define PSTADE_TOMATO_WORKAROUND_ATL_CSIMPLESTRINGT_TEMPLATE_PARAMS class BaseT, bool mfcdll
	#define PSTADE_TOMATO_WORKAROUND_ATL_CSIMPLESTRINGT_TEMPLATE_ARGS BaseT, mfcdll 
#else
	#define PSTADE_TOMATO_WORKAROUND_ATL_CSIMPLESTRINGT_TEMPLATE_PARAMS class BaseT
	#define PSTADE_TOMATO_WORKAROUND_ATL_CSIMPLESTRINGT_TEMPLATE_ARGS BaseT
#endif
