#ifndef BOOST_EGG_DETAIL_AMBI_MACROS_HPP
#define BOOST_EGG_DETAIL_AMBI_MACROS_HPP


// Boost.Egg
//
// Copyright Shunsuke Sogame 2007-2008.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)


// What:
//
// This is needed only for the macro naming convention.


#define BOOST_EGG_AMBI0_L BOOST_EGG_AMBI_L
#define BOOST_EGG_AMBI0_R BOOST_EGG_AMBI_R

#define BOOST_EGG_AMBI1_L BOOST_EGG_AMBI_L
#define BOOST_EGG_AMBI1_R BOOST_EGG_AMBI_R

#define BOOST_EGG_AMBI2_L BOOST_EGG_AMBI_L
#define BOOST_EGG_AMBI2_R BOOST_EGG_AMBI_R

#define BOOST_EGG_AMBI3_L BOOST_EGG_AMBI_L
#define BOOST_EGG_AMBI3_R BOOST_EGG_AMBI_R

#define BOOST_EGG_AMBI4_L BOOST_EGG_AMBI_L
#define BOOST_EGG_AMBI4_R BOOST_EGG_AMBI_R

#define BOOST_EGG_AMBI5_L BOOST_EGG_AMBI_L
#define BOOST_EGG_AMBI5_R BOOST_EGG_AMBI_R

#define BOOST_EGG_AMBI6_L BOOST_EGG_AMBI_L
#define BOOST_EGG_AMBI6_R BOOST_EGG_AMBI_R

#define BOOST_EGG_AMBI7_L BOOST_EGG_AMBI_L
#define BOOST_EGG_AMBI7_R BOOST_EGG_AMBI_R

#define BOOST_EGG_AMBI8_L BOOST_EGG_AMBI_L
#define BOOST_EGG_AMBI8_R BOOST_EGG_AMBI_R

#define BOOST_EGG_AMBI9_L BOOST_EGG_AMBI_L
#define BOOST_EGG_AMBI9_R BOOST_EGG_AMBI_R


// #define BOOST_EGG_AMBI(N) BOOST_PP_CAT(BOOST_EGG_AMBI, N)
#define BOOST_EGG_AMBI0(F) BOOST_EGG_AMBI0_L F BOOST_EGG_AMBI0_R
#define BOOST_EGG_AMBI1(F) BOOST_EGG_AMBI1_L F BOOST_EGG_AMBI1_R
#define BOOST_EGG_AMBI2(F) BOOST_EGG_AMBI2_L F BOOST_EGG_AMBI2_R
#define BOOST_EGG_AMBI3(F) BOOST_EGG_AMBI3_L F BOOST_EGG_AMBI3_R
#define BOOST_EGG_AMBI4(F) BOOST_EGG_AMBI4_L F BOOST_EGG_AMBI4_R
#define BOOST_EGG_AMBI5(F) BOOST_EGG_AMBI5_L F BOOST_EGG_AMBI5_R
#define BOOST_EGG_AMBI6(F) BOOST_EGG_AMBI6_L F BOOST_EGG_AMBI6_R
#define BOOST_EGG_AMBI7(F) BOOST_EGG_AMBI7_L F BOOST_EGG_AMBI7_R
#define BOOST_EGG_AMBI8(F) BOOST_EGG_AMBI8_L F BOOST_EGG_AMBI8_R
#define BOOST_EGG_AMBI9(F) BOOST_EGG_AMBI9_L F BOOST_EGG_AMBI9_R


#endif
