#ifndef PSTADE_EGG_EGG_HPP
#define PSTADE_EGG_EGG_HPP


// PStade.Egg
//
// Copyright Shunsuke Sogame 2007.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)


#include "./adapt.hpp"
#include "./adapt_sig.hpp"
#include "./adaptable.hpp"
#include "./always.hpp"
#include "./apply_params.hpp"
#include "./auto_object.hpp"
#include "./automatic.hpp"
#include "./auxiliary.hpp"
#include "./config.hpp"
#include "./construct.hpp"
#include "./constructor.hpp"
#include "./copy.hpp"
#include "./copy_assign.hpp"
#include "./delete.hpp"
#include "./delete_array.hpp"
#include "./dereference.hpp"
#include "./divides.hpp"
#include "./do_swap.hpp"
#include "./equal_to.hpp"
#include "./equal_to_0.hpp"
#include "./flip.hpp"
#include "./function.hpp"
#include "./function_facade.hpp"
#include "./function_by_value.hpp"
#include "./function_fwd.hpp"
#include "./fuse.hpp"
#include "./generator.hpp"
#include "./greater.hpp"
#include "./greater_equal.hpp"
#include "./identity.hpp"
#include "./iequal_to.hpp"
#include "./indirected.hpp"
#include "./integral_cast.hpp"
#include "./integralize.hpp"
#include "./is_classified_as.hpp"
#include "./is_same.hpp"
#include "./lambda_bind.hpp"
#include "./lambda_placeholders.hpp"
#include "./less.hpp"
#include "./less_equal.hpp"
#include "./lexical_cast.hpp"
#include "./lexicalize.hpp"
#include "./logical_and.hpp"
#include "./logical_not.hpp"
#include "./logical_or.hpp"
#include "./make_function.hpp"
#include "./make_function_by_value.hpp"
#include "./minus.hpp"
#include "./modulus.hpp"
#include "./multiplies.hpp"
#include "./negate.hpp"
#include "./new.hpp"
#include "./new_array.hpp"
#include "./new_auto.hpp"
#include "./new_ptr.hpp"
#include "./new_shared.hpp"
#include "./new_shared_array.hpp"
#include "./not.hpp"
#include "./nullary_result_of.hpp"
#include "./perfect.hpp"
#include "./pipable.hpp"
#include "./plus.hpp"
#include "./ret.hpp"
#include "./shared_object.hpp"
#include "./sig_template.hpp"
#include "./specified.hpp"
#include "./static_downcast.hpp"
#include "./swap_assign.hpp"
#include "./to_lower.hpp"
#include "./to_ref.hpp"
#include "./to_shared_ptr.hpp"
#include "./to_string.hpp"
#include "./to_upper.hpp"
#include "./to_value.hpp"
#include "./tuple_element.hpp"
#include "./tuple_get.hpp"
#include "./tuple_pack.hpp"
#include "./tuple_size.hpp"
#include "./unfuse.hpp"
#include "./use_brace_level0.hpp"
#include "./use_brace_level1.hpp"
#include "./use_constructor.hpp"


#endif
