#pragma once

#include <boost/config.hpp> // for BOOST_NO_ARGUMENT_DEPENDENT_LOOKUP
#include <boost/preprocessor/seq/for_each.hpp>


#if !defined(BOOST_NO_ARGUMENT_DEPENDENT_LOOKUP)

		#define PSTADE_WORKAROUND_NO_ADL_CUSTOMIZATION_DETAL_OPEN(r, data, elem) \
			namespace elem { \
		/**/

		#define PSTADE_WORKAROUND_NO_ADL_CUSTOMIZATION_DETAL_CLOSE(r, data, elem) \
			} \
		/**/

	#define PSTADE_WORKAROUND_NO_ADL_CUSTOMIZATION_OPEN(seq) \
		BOOST_PP_SEQ_FOR_EACH(PSTADE_WORKAROUND_NO_ADL_CUSTOMIZATION_DETAL_OPEN, ~, seq) \
	/**/

	#define PSTADE_WORKAROUND_NO_ADL_CUSTOMIZATION_CLOSE(seq) \
		BOOST_PP_SEQ_FOR_EACH(PSTADE_WORKAROUND_NO_ADL_CUSTOMIZATION_DETAL_CLOSE, ~, seq) \
	/**/

#else

	#define PSTADE_WORKAROUND_NO_ADL_CUSTOMIZATION_OPEN(seq) \
	/**/

	#define PSTADE_WORKAROUND_NO_ADL_CUSTOMIZATION_CLOSE(seq) \
	/**/

#endif // !defined(BOOST_NO_ARGUMENT_DEPENDENT_LOOKUP)

