
namespace pstade { namespace biscuit {

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch8 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch9 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch10 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch11 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch12 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch13 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch14 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch15 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch16 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch17 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch18 = 0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch19 = 0
	>
	struct bchseq :
		bchseq20<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13 , ch14 , ch15 , ch16 , ch17 , ch18 , ch19
		>
	{
	};

	template<
		class T 
	>
	struct bchseq<
		T 
	> :
	bchseq0<
		T 
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0
	>
	struct bchseq<
		T ,
		ch0
	> :
	bchseq1<
		T ,
		ch0
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1
	>
	struct bchseq<
		T ,
		ch0 , ch1
	> :
	bchseq2<
		T ,
		ch0 , ch1
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2
	> :
	bchseq3<
		T ,
		ch0 , ch1 , ch2
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3
	> :
	bchseq4<
		T ,
		ch0 , ch1 , ch2 , ch3
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4
	> :
	bchseq5<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5
	> :
	bchseq6<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6
	> :
	bchseq7<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7
	> :
	bchseq8<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch8
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8
	> :
	bchseq9<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch8 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch9
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9
	> :
	bchseq10<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch8 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch9 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch10
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10
	> :
	bchseq11<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch8 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch9 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch10 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch11
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11
	> :
	bchseq12<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch8 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch9 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch10 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch11 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch12
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12
	> :
	bchseq13<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch8 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch9 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch10 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch11 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch12 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch13
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13
	> :
	bchseq14<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch8 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch9 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch10 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch11 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch12 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch13 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch14
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13 , ch14
	> :
	bchseq15<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13 , ch14
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch8 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch9 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch10 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch11 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch12 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch13 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch14 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch15
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13 , ch14 , ch15
	> :
	bchseq16<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13 , ch14 , ch15
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch8 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch9 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch10 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch11 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch12 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch13 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch14 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch15 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch16
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13 , ch14 , ch15 , ch16
	> :
	bchseq17<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13 , ch14 , ch15 , ch16
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch8 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch9 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch10 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch11 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch12 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch13 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch14 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch15 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch16 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch17
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13 , ch14 , ch15 , ch16 , ch17
	> :
	bchseq18<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13 , ch14 , ch15 , ch16 , ch17
	>
	{
	};

	template<
		class T ,
			PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch0 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch1 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch2 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch3 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch4 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch5 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch6 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch7 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch8 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch9 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch10 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch11 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch12 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch13 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch14 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch15 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch16 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch17 , PSTADE_BISCUIT_CHARACTER_HOLDER_TYPE ch18
	>
	struct bchseq<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13 , ch14 , ch15 , ch16 , ch17 , ch18
	> :
	bchseq19<
		T ,
		ch0 , ch1 , ch2 , ch3 , ch4 , ch5 , ch6 , ch7 , ch8 , ch9 , ch10 , ch11 , ch12 , ch13 , ch14 , ch15 , ch16 , ch17 , ch18
	>
	{
	};

} }
