#ifndef PSTADE_OVEN_ADAPTORS_HPP
#define PSTADE_OVEN_ADAPTORS_HPP


// PStade.Oven
//
// Copyright Shunsuke Sogame 2005-2007.
// Distributed under the Boost Software License, Version 1.0. 
// (See accompanying file LICENSE_1_0.txt or copy at 
// http://www.boost.org/LICENSE_1_0.txt)


#include "./adjacent_filtered.hpp"
#include "./adjacent_transformed.hpp"
#include "./always.hpp"
#include "./appended.hpp"
#include "./applied.hpp"
#include "./broken_into.hpp"
#include "./checked.hpp"
#include "./cleared.hpp"
#include "./concatenated.hpp"
#include "./const_lvalues.hpp"
#include "./constants.hpp"
#include "./copied_out.hpp"
#include "./cycled.hpp"
#include "./delimited.hpp"
#include "./dropped.hpp"
#include "./dropped_while.hpp"
#include "./filtered.hpp"
#include "./firsts.hpp"
// #include "./got_at.hpp"
#include "./identities.hpp"
#include "./indirected.hpp"
#include "./jointed.hpp"
#include "./map_keys.hpp"
#include "./map_values.hpp"
// #include "./matches.hpp"
// #include "./mb_decoded.hpp"
// #include "./mb_encoded.hpp"
#include "./memoized.hpp"
#include "./merged.hpp"
// #include "./moved.hpp"
#include "./offset.hpp"
#include "./outdirected.hpp"
#include "./outplaced.hpp"
#include "./permuted.hpp"
#include "./pointed.hpp"
#include "./popped.hpp"
#include "./prepended.hpp"
#include "./reversed.hpp"
#include "./rotated.hpp"
#include "./scanned.hpp"
#include "./seconds.hpp"
#include "./set_cap.hpp"
#include "./set_cup.hpp"
#include "./set_delta.hpp"
#include "./set_minus.hpp"
#include "./shared.hpp"
#include "./sliced.hpp"
#include "./sorted.hpp"
#include "./spanned.hpp"
#include "./split_at.hpp"
#include "./string_found.hpp"
#include "./string_split.hpp"
#include "./successors.hpp"
#include "./tab_expanded.hpp"
#include "./tab_unexpanded.hpp"
#include "./taken.hpp"
#include "./taken_while.hpp"
// #include "./tokenized.hpp"
#include "./transformed.hpp"
#include "./uniqued.hpp"
#include "./unzipped.hpp"
#include "./utf8_decoded.hpp"
#include "./utf8_encoded.hpp"
#include "./window.hpp"
#include "./with_position.hpp"
#include "./xpressive_matches.hpp"
#include "./xpressive_tokenized.hpp"
#include "./zipped.hpp"
#include "./zipped_with.hpp"


#endif
