#ifndef PSTADE_OVEN_RANGES_HPP
#define PSTADE_OVEN_RANGES_HPP


// PStade.Oven
//
// Copyright MB 2005-2006.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)


#include "./adjacent_filter_range.hpp"
#include "./always_range.hpp"
#include "./append_range.hpp"
#include "./apply_range.hpp"
#include "./array_protect_range.hpp"
#include "./array_range.hpp"
#include "./break_into_range.hpp"
#include "./check_range.hpp"
#include "./clear_range.hpp"
#include "./concatenate_range.hpp"
#include "./constant_range.hpp"
#include "./const_lvalue_range.hpp"
#include "./copy_range.hpp"
#include "./counting_range.hpp"
// #include "./directory_range.hpp"
#include "./direct_range.hpp"
#include "./drop_range.hpp"
#include "./drop_while_range.hpp"
#include "./empty_range.hpp"
#include "./file_range.hpp"
#include "./filter_range.hpp"
#include "./first_range.hpp"
// #include "./get_at_range.hpp"
#include "./identity_range.hpp"
#include "./indirect_range.hpp"
#include "./istream_range.hpp"
#include "./istreambuf_range.hpp"
#include "./joint_range.hpp"
#include "./map_key_range.hpp"
#include "./map_value_range.hpp"
// #include "./match_range.hpp"
// #include "./mb_decode_range.hpp"
// #include "./mb_encode_range.hpp"
#include "./memoize_range.hpp"
#include "./multi_pass_range.hpp"
#include "./null_terminate_range.hpp"
#include "./out_place_range.hpp"
#include "./permute_range.hpp"
#include "./point_range.hpp"
#include "./position_range.hpp"
#include "./prepend_range.hpp"
#include "./regularize_range.hpp"
#include "./repeat_range.hpp"
#include "./reverse_range.hpp"
#include "./scan_range.hpp"
#include "./second_range.hpp"
#include "./share_range.hpp"
#include "./shift_range.hpp"
#include "./single_range.hpp"
#include "./slice_range.hpp"
#include "./sort_range.hpp"
#include "./stride_range.hpp"
#include "./string_find_range.hpp"
#include "./string_split_range.hpp"
#include "./sub_set.hpp"
#include "./tab_expand_range.hpp"
#include "./tab_unexpand_range.hpp"
#include "./take_range.hpp"
#include "./take_while_range.hpp"
// #include "./token_range.hpp"
#include "./transform_range.hpp"
#include "./unique_range.hpp"
#include "./unzip_range.hpp"
#include "./utf8_decode_range.hpp"
#include "./utf8_encode_range.hpp"
// #include "./xpressive_match_range.hpp"
// #include "./xpressive_token_range.hpp"
#include "./zip_range.hpp"
#include "./zip_with_range.hpp"


#endif
